azuredevops:
  - name: azdo-dbw-az
    organization: dougbw
    cloneMethod: ssh
    include: azure
    destination: "./azdo/dougbw/azure"
    cli: true

github:
  - name: github-dougbw
    owner: dougbw
    cloneMethod: https
    include: pwsh
    destination: "./github/dougbw"

  - name: github-amido-techops
    owner: amido
    cloneMethod: https
    include: techops
    destination: ./github/amido/techops

  - name: github-amido-stacks
    owner: amido
    cloneMethod: https
    include: stacks
    destination: ./github/amido/stacks

gitlab:
  - name: gitlab-dougbw1
    user: dougbw1
    cloneMethod: https
    destination: "./gitlab/dougbw1"
